import scrapy

class JohnlewisItem(scrapy.Item):
    #brand = scrapy.Field()
    #Productnumber = scrapy.Field()
    Url = scrapy.Field()
    Category = scrapy.Field()
    Price = scrapy.Field()
    Description = scrapy.Field()
    Composition = scrapy.Field()
    Polyester = scrapy.Field()
    Elastane = scrapy.Field()
    Cotton = scrapy.Field()
    Viscose = scrapy.Field()
    Polyamide = scrapy.Field()
    Linen = scrapy.Field()
    Triacetate = scrapy.Field()
    Lyocell = scrapy.Field()
    Lenzing_Ecovero = scrapy.Field()
    Velvet = scrapy.Field()
    Lace = scrapy.Field()
    Wool = scrapy.Field()
    Silk = scrapy.Field()
    Satin = scrapy.Field()
    Chiffon = scrapy.Field()
    Leather = scrapy.Field()
    Polyurethane = scrapy.Field()
    Suede = scrapy.Field()
    Spandex = scrapy.Field()
    Acrylic = scrapy.Field()
    Nylon = scrapy.Field()
    Cashmere = scrapy.Field()
    Cupro = scrapy.Field()
    Rayon = scrapy.Field()
    Modal = scrapy.Field()
    Acetate = scrapy.Field()
